title: FOnline: The Life After
description: Fallout-like game based on FOnline engine
email: cvet@tut.by
theme: jekyll-theme-slate
exclude:
  - Critters/
  - Dialogs/
  - Engine/
  - Gui/
  - Items/
  - Maps/
  - Resources/
  - Scripts/
  - Texts/
